# Generated by Django 4.1.2 on 2022-12-03 13:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('Budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('UAH_amount', models.IntegerField(default=0)),
                ('USD_amount', models.IntegerField(default=0)),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('TH_id', models.AutoField(primary_key=True, serialize=False)),
                ('Currency', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('TransactionTime', models.DateTimeField(auto_now_add=True)),
                ('Sender_id', models.CharField(max_length=1638, validators=[django.core.validators.MinLengthValidator(1)])),
                ('Receiver_id', models.CharField(max_length=1638, validators=[django.core.validators.MinLengthValidator(1)])),
                ('Budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget.budget')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
