# Generated by Django 4.1.2 on 2022-10-20 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='Date_created',
            field=models.DateField(default=datetime.datetime(2022, 10, 20, 17, 0, 58, 262308, tzinfo=datetime.timezone.utc)),
        ),
    ]
