# Generated by Django 4.1.2 on 2022-10-20 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0002_alter_budget_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='Date_created',
            field=models.DateField(default=datetime.datetime(2022, 10, 20, 17, 49, 30, 218018, tzinfo=datetime.timezone.utc)),
        ),
    ]
