# Generated by Django 4.1.2 on 2022-12-03 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('Family_id', models.AutoField(primary_key=True, serialize=False)),
                ('FamilyName', models.CharField(default='New_Family', max_length=24, validators=[django.core.validators.MinLengthValidator(3)])),
                ('FamilyMembers', models.IntegerField()),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyRole',
            fields=[
                ('FamilyRole_id', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(choices=[('Administrator', 'Administrator'), ('Member', 'Member')], default='Member', max_length=14, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpendingLimit', models.IntegerField(default=0)),
                ('RegisteredDay', models.DateTimeField(auto_now_add=True)),
                ('Family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.family')),
                ('FamilyRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.familyrole')),
            ],
        ),
    ]
